/* 2024
Evaluates monthly holding expenses generated by products
 meeting baseline safety stock requirements (adequate_stock) while failing to cover anticipated 
 sales across supplier lead times (insufficient_coverage).
 Quantifies the capital tied up in warehousing items that remain exposed to stockout risks before replenishment arrives
*/


WITH safety_level AS (

SELECT 
s.productid,
s.date,
round(avg(s.quantity_sales)::numeric,2) as avg_quantity_sales,
round(avg(I.inventory_level)::numeric,2) as avg_inventory_month,
pp.safety_stock_months,
pp.lead_time_months,
round(avg(quantity_sales*pp.lead_time_months)::numeric,2) as lead_time_sales,
pp.storage_cost_pln_per_unit_month,

-- livello minimo di unita da mentere nel mese
round(avg(s.quantity_sales)::numeric * pp.safety_stock_months::numeric,2) as Min_level_per_month

FROM sales_2023_2024 as s

JOIN inventory_2023_2024 as I ON
I.productid = s.productid
and I.date = s.date

JOIN product_parameter as pp On
pp.productid = s.productid

group by s.productid, s.date, I.inventory_level, pp.safety_stock_months, pp.lead_time_months,pp.storage_cost_pln_per_unit_month
order by s.productid, s.date
),


case_level AS (
SELECT
*,
case
when Min_level_per_month < avg_inventory_month then 'adequate_stock'
when Min_level_per_month > avg_inventory_month then 'stockout_risk'
else 'avg_level'
end as level_stock
FROM safety_level
),

lead_time_risk AS (
SELECT
*,
case
when avg_inventory_month < lead_time_sales then 'insufficient_coverage' 
when avg_inventory_month > lead_time_sales then 'sufficient_coverage'
else 'avg_level'
end as lead_time_coverage_status
from case_level
)


select 
productid, 
date,
lead_time_sales,
min_level_per_month,
level_stock,
lead_time_coverage_status,
storage_cost_pln_per_unit_month,
avg_inventory_month,
round(avg_inventory_month * storage_cost_pln_per_unit_month::numeric,2) as storage_cost_pln_per_month

from lead_time_risk
where level_stock = 'adequate_stock' and lead_time_coverage_status = 'insufficient_coverage'
group by productid, date, lead_time_sales, min_level_per_month, level_stock, lead_time_coverage_status, storage_cost_pln_per_unit_month, avg_inventory_month

order by storage_cost_pln_per_month desc



-- sum of storage cost for all products at risk of stockout by lead time


SELECT sum(storage_cost_pln_per_month) as totale_costo_stoccaggio,
year
FROM (

    WITH safety_level AS (

    SELECT 
    s.productid,
    s.date,
    round(avg(s.quantity_sales)::numeric,2) as avg_quantity_sales,
    round(avg(I.inventory_level)::numeric,2) as avg_inventory_month,
    pp.safety_stock_months,
    pp.lead_time_months,
    round(avg(quantity_sales*pp.lead_time_months)::numeric,2) as lead_time_sales,
    pp.storage_cost_pln_per_unit_month,
    round(avg(s.quantity_sales)::numeric * pp.safety_stock_months::numeric,2) as Min_level_per_month

    FROM sales_2023_2024 as s
    JOIN inventory_2023_2024 as I ON
        I.productid = s.productid
        and I.date = s.date
    JOIN product_parameter as pp On
        pp.productid = s.productid

    group by s.productid, s.date, I.inventory_level, pp.safety_stock_months, pp.lead_time_months, pp.storage_cost_pln_per_unit_month
    order by s.productid, s.date
    ),

case_level AS (
SELECT
*,
case
when Min_level_per_month < avg_inventory_month then 'adequate_stock'
when Min_level_per_month > avg_inventory_month then 'stockout_risk'
else 'avg_level'
end as level_stock
FROM safety_level
),

lead_time_risk AS (
SELECT
*,
case
when avg_inventory_month < lead_time_sales then 'insufficient_coverage' 
when avg_inventory_month > lead_time_sales then 'sufficient_coverage'
else 'avg_level'
end as lead_time_coverage_status
from case_level
)

    select 
    productid, 
    extract(year from date) as year, 
    lead_time_sales,
    min_level_per_month,
    level_stock,
    lead_time_coverage_status,
    storage_cost_pln_per_unit_month,
    avg_inventory_month,
    round(avg_inventory_month * storage_cost_pln_per_unit_month::numeric,2) as storage_cost_pln_per_month

    from lead_time_risk
    where level_stock = 'adequate_stock' and lead_time_coverage_status = 'insufficient_coverage'
    group by productid, extract(year from date), lead_time_sales, min_level_per_month, level_stock, lead_time_coverage_status, storage_cost_pln_per_unit_month, avg_inventory_month

) as t

group by year
order by year;


